### ISSUE TITLE
Exponentiation!

### ISSUE THREAD

**Issue by LucasCardoso910** [DOS-Desenvolvimento-Open-Source/calculadora#1]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to use this program to calculate an exponentiation! I must to multiplicate the same number several times when I want to calculate, for example, 2^10! It is really upsetting! This program should have something already done to do this!

**Describe the solution you'd like**
I'd like to be able to write 'e' (from exponentiation) and type two numbers a and b and the program should give me as result a^b.

**Describe alternatives you've considered**
I believe the best way to correct this would be to use the function pow from the cmath library. Or even to loop 10 times the operation of 2*2 and return the result.

**Comment by rrligeiro** [comment]
I will do this using de cmath library, because i think it will be useful later!

**Comment by rrligeiro** [comment]
I'm closing this Issue, because i already sent de PR.
